#!/usr/bin/env bash

LOGSTASH_CONFIG_FILE=/opt/logstash/logstash.conf

cp ./config/logstash.conf /opt/logstash/logstash.conf

# Fire up logstash!
exec /opt/logstash/bin/logstash \
    agent \
    --config /opt/ $LOGSTASH_CONFIG_FILE \
    -- \
    web 