#!/usr/bin/env bash

#LOGSTASH_CONFIG_FILE=""

cp ./config/logstash.conf /opt/logstash/logstash.conf 

# Fire up logstash!
exec /opt/logstash/bin/logstash \
    agent \
    --config  /opt/logstash/logstash.conf \
    -- \
    web 